# Generated by Django 5.1.6 on 2025-02-19 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('total_copies', models.IntegerField()),
                ('available_copies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book'),
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.member')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.materialtype'),
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='borrow',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
